version: "3.8"

networks:
  prod_net:
    driver: bridge

services:
  serving-api:
    container_name: serving-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api.py:/app/api.py
      - ../data:/data
      - ../artifacts:/artifacts
      - ../scripts/fct_model.py:/app/fct_model.py
    ports:
      - "8080:8080"
    networks:
      - prod_net
